// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gfx6XEav11wd1hD0_QZd_OMLrpLs0iM',
    appId: '1:247904704057:web:4eeebb7300097ac1755fe8',
    messagingSenderId: '247904704057',
    projectId: 'thesis-7e717',
    authDomain: 'thesis-7e717.firebaseapp.com',
    databaseURL: 'https://thesis-7e717-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-7e717.firebasestorage.app',
    measurementId: 'G-T3F8YEE2GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNS71ccFcFER6ZO4pCFP6v-W-jVmv1bs',
    appId: '1:247904704057:android:b6f1cfdd842bfcc3755fe8',
    messagingSenderId: '247904704057',
    projectId: 'thesis-7e717',
    databaseURL: 'https://thesis-7e717-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-7e717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqowoPfXDCNAHsq3RC2A4dUv9ZNTmuYm8',
    appId: '1:247904704057:ios:a4cfe8697841ce82755fe8',
    messagingSenderId: '247904704057',
    projectId: 'thesis-7e717',
    databaseURL: 'https://thesis-7e717-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-7e717.firebasestorage.app',
    iosClientId: '247904704057-qjd4p5cse88auo8prah1f48aqtq2k899.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqowoPfXDCNAHsq3RC2A4dUv9ZNTmuYm8',
    appId: '1:247904704057:ios:a4cfe8697841ce82755fe8',
    messagingSenderId: '247904704057',
    projectId: 'thesis-7e717',
    databaseURL: 'https://thesis-7e717-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-7e717.firebasestorage.app',
    iosClientId: '247904704057-qjd4p5cse88auo8prah1f48aqtq2k899.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4gfx6XEav11wd1hD0_QZd_OMLrpLs0iM',
    appId: '1:247904704057:web:4cc798948659f6e0755fe8',
    messagingSenderId: '247904704057',
    projectId: 'thesis-7e717',
    authDomain: 'thesis-7e717.firebaseapp.com',
    databaseURL: 'https://thesis-7e717-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'thesis-7e717.firebasestorage.app',
    measurementId: 'G-J292PH3ZSQ',
  );

}